apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: microsponsoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      securityContext:
        runAsUser: 0
      nodeSelector:
        kubernetes.io/hostname: "workernode1-vmware-virtual-platform"
      containers:
      - name: frontend
        image: medbaha/pfefrontend:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: images-storage
          mountPath: /usr/share/nginx/html/images
      volumes:
      - name: images-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: microsponsoring
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
