apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"mysql"},"name":"mysql-service","namespace":"microsponsoring"},"spec":{"ports":[{"port":3306,"targetPort":3306}],"selector":{"app":"mysql"},"type":"ClusterIP"}}
  creationTimestamp: "2025-10-04T18:39:00Z"
  labels:
    app: mysql
  name: mysql
  namespace: microsponsoring
  resourceVersion: "93970"
  uid: 36ef1548-8731-43d2-b29e-fde647fd9269
spec:
  clusterIP: 10.105.98.203
  clusterIPs:
  - 10.105.98.203
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
