apiVersion: v1
kind: Namespace
metadata:
  name: microsponsoring
  labels:
    name: microsponsoring
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: microsponsoring-staging
  labels:
    name: microsponsoring-staging
    environment: staging 