apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-pvc
  namespace: microsponsoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: invoices-pvc
  namespace: microsponsoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
