apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-headers
  namespace: microsponsoring
data:
  Upgrade: "$http_upgrade"
  Connection: "$connection_upgrade"
  Host: "$host"
  X-Real-IP: "$remote_addr"
  X-Forwarded-For: "$proxy_add_x_forwarded_for"
  X-Forwarded-Proto: "$scheme"
